import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {BrowserRouter,useLocation,useNavigate,useParams,Link,NavLink,Routes,Route} from "react-router-dom";
import Editor from "@monaco-editor/react";
import {
 Activity,AlertCircle,ArrowLeft,ArrowRight,BarChart3,Bell,BookOpen,BrainCircuit,CalendarDays,
 Check,CheckCircle2,ChevronDown,ChevronLeft,ChevronRight,Clock3,Code2,Command,Copy,Database,
 Download,Edit3,FileCode2,Filter,Flame,Globe2,GraduationCap,KeyRound,LayoutDashboard,LifeBuoy,
 LineChart as LineIcon,LogIn,LogOut,Menu,MessageSquare,MoreHorizontal,Moon,PanelLeft,Play,
 Plus,RefreshCw,Search,Send,Settings,ShieldCheck,SlidersHorizontal,Sparkles,Sun,Target,
 Terminal,Trophy,Upload,User,UserCheck,Users,X,Zap
} from "lucide-react";
import {LineChart,Line,BarChart,Bar,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell,AreaChart,Area} from "recharts";
import "./styles.css";

const problems=[
{id:1,title:"Two Sum",difficulty:"Easy",topic:"Arrays",points:100,acceptance:82},
{id:2,title:"Valid Parentheses",difficulty:"Easy",topic:"Stack",points:100,acceptance:76},
{id:3,title:"Longest Substring Without Repeating Characters",difficulty:"Medium",topic:"Strings",points:180,acceptance:68},
{id:4,title:"Merge Intervals",difficulty:"Medium",topic:"Arrays",points:200,acceptance:61},
{id:5,title:"Binary Tree Maximum Path Sum",difficulty:"Hard",topic:"Trees",points:300,acceptance:42},
{id:6,title:"Number of Islands",difficulty:"Medium",topic:"Graphs",points:220,acceptance:71},
{id:7,title:"LRU Cache",difficulty:"Hard",topic:"Design",points:320,acceptance:39},
{id:8,title:"Climbing Stairs",difficulty:"Easy",topic:"Dynamic Programming",points:100,acceptance:88},
{id:9,title:"Kth Largest Element",difficulty:"Medium",topic:"Heap",points:210,acceptance:64},
{id:10,title:"Word Ladder",difficulty:"Hard",topic:"Graphs",points:350,acceptance:37},
{id:11,title:"Course Schedule",difficulty:"Medium",topic:"Graphs",points:220,acceptance:59},
{id:12,title:"House Robber",difficulty:"Medium",topic:"Dynamic Programming",points:170,acceptance:73}
];
const contests=[
{id:1,name:"CodeArena Weekly #42",status:"Live",difficulty:"Medium",problems:5,participants:1248,duration:"90 min",time:"24m"},
{id:2,name:"Python Sprint",status:"Upcoming",difficulty:"Easy",problems:4,participants:643,duration:"60 min",time:"Tomorrow"},
{id:3,name:"Campus Championship",status:"Upcoming",difficulty:"Hard",problems:8,participants:2180,duration:"150 min",time:"2 days"},
{id:4,name:"Algorithms Night",status:"Completed",difficulty:"Medium",problems:6,participants:932,duration:"120 min",time:"Completed"}
];
const leaderboard=[
{rank:1,name:"Aarav Mehta",score:986,rating:2140,solved:10,accuracy:98,time:"42m",smart:98.4},
{rank:2,name:"Diya Shah",score:954,rating:2098,solved:9,accuracy:96,time:"47m",smart:97.2},
{rank:3,name:"Rohan Patel",score:928,rating:2054,solved:9,accuracy:94,time:"51m",smart:95.8},
{rank:4,name:"Kritarth Joshi",score:892,rating:1987,solved:8,accuracy:91,time:"56m",smart:93.6},
{rank:5,name:"Ananya Rao",score:874,rating:1962,solved:8,accuracy:90,time:"61m",smart:92.1},
{rank:6,name:"Dev Malhotra",score:841,rating:1911,solved:7,accuracy:88,time:"64m",smart:90.5}
];
const activity=[{day:"Mon",sub:48,score:71},{day:"Tue",sub:72,score:78},{day:"Wed",sub:55,score:75},{day:"Thu",sub:91,score:86},{day:"Fri",sub:84,score:83},{day:"Sat",sub:116,score:94},{day:"Sun",sub:96,score:89}];
const initialCode=`def two_sum(nums, target):
    seen = {}

    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i

    return []`;

function useTheme(){
 const [light,setLight]=useState(()=>localStorage.getItem("ca-theme")==="light");
 useEffect(()=>{document.documentElement.dataset.theme=light?"light":"dark";localStorage.setItem("ca-theme",light?"light":"dark")},[light]);
 return [light,setLight];
}
function Brand(){return <Link to="/" className="brand"><span className="brand-mark"><Code2 size={18}/></span><b>Code</b><b className="brand-muted">Arena</b></Link>}
function Badge({children,type=""}){return <span className={"badge "+type.toLowerCase().replaceAll(" ","-")}>{children}</span>}
function Button({children,primary=false,small=false,className="",...p}){return <button className={`btn ${primary?"primary":""} ${small?"small":""} ${className}`} {...p}>{children}</button>}
function Toast({message,onClose}){return <div className="toast"><CheckCircle2 size={17}/><span>{message}</span><button onClick={onClose}><X size={14}/></button></div>}

function Landing(){
 const [light,setLight]=useTheme(); const [menu,setMenu]=useState(false);
 return <div className="landing">
  <nav className="public-nav"><Brand/><button className="mobile-only icon-btn" onClick={()=>setMenu(!menu)}><Menu/></button>
   <div className={`public-links ${menu?"show":""}`}><a href="#features">Features</a><a href="#roles">Roles</a><a href="#workflow">How it works</a><Link to="/login">Login</Link><Button primary onClick={()=>location.href="/register"}>Get started <ArrowRight size={15}/></Button><button className="theme-toggle" onClick={()=>setLight(!light)}>{light?<Moon size={16}/>:<Sun size={16}/>}</button></div>
  </nav>
  <section className="hero public-wrap">
   <div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> INSTITUTIONAL CODING, REIMAGINED</div><h1>Code. Compete.<br/><span>Conquer.</span></h1><p>A complete coding assessment ecosystem for students, faculty and administrators — with contests, secure evaluation, analytics and intelligent rankings.</p><div className="hero-actions"><Link to="/register" className="btn primary big">Start coding <ArrowRight size={17}/></Link><Link to="/contests" className="btn big"><Trophy size={17}/> Explore contests</Link></div><div className="hero-proof"><span><ShieldCheck size={15}/> Secure evaluation</span><span><Zap size={15}/> Instant feedback</span><span><BrainCircuit size={15}/> Smart analytics</span></div></div>
   <div className="hero-dashboard"><div className="hero-glow"/><div className="mock-window"><div className="mock-top"><span className="window-dots"><i/><i/><i/></span><span>student-dashboard</span><span className="live-label">LIVE</span></div><div className="mock-body"><div className="mini-stat"><small>Contest rating</small><strong>1,987</strong><em>↑ 126</em></div><div className="mini-stat"><small>Current rank</small><strong>#4</strong><em>↑ 8</em></div><div className="mini-chart"><div className="mini-chart-head"><span>Performance</span><span>7 days</span></div><ResponsiveContainer width="100%" height={120}><AreaChart data={activity}><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#6978ff" stopOpacity=".35"/><stop offset="100%" stopColor="#6978ff" stopOpacity="0"/></linearGradient></defs><Area type="monotone" dataKey="score" stroke="#6978ff" fill="url(#g)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div><div className="mini-row"><span><CheckCircle2/> Two Sum</span><Badge type="accepted">Accepted</Badge></div><div className="mini-row"><span><Trophy/> Weekly #42</span><b>#4 / 1248</b></div></div></div></div>
  </section>
  <section className="metric-band"><div><b>10K+</b><span>Students</span></div><div><b>500+</b><span>Problems</span></div><div><b>100+</b><span>Contests</span></div><div><b>98%</b><span>Evaluation accuracy</span></div></section>
  <section id="features" className="public-section public-wrap"><div className="section-heading"><div className="eyebrow">ONE PLATFORM, EVERY WORKFLOW</div><h2>Everything a coding institution needs.</h2><p>Designed around the real workflow of students, faculty and system administrators.</p></div><div className="feature-grid">{[
["Automated evaluation",Terminal,"Run submissions against predefined test cases with consistent results."],
["Integrated IDE",FileCode2,"A focused Monaco-powered coding workspace with run, submit and test tools."],
["Live leaderboards",Trophy,"Real-time ranking with accuracy, speed, difficulty and smart score."],
["Faculty control",GraduationCap,"Create contests, curate problems, schedule exams and review results."],
["Performance intelligence",BrainCircuit,"Surface trends, weak areas and meaningful progress insights."],
["Institution control",ShieldCheck,"Role-based access, user management, audit-ready analytics and settings."]
].map(([t,I,d])=><div className="feature-card" key={t}><div className="feature-icon"><I/></div><h3>{t}</h3><p>{d}</p><ArrowRight className="feature-arrow" size={16}/></div>)}</div></section>
  <section id="roles" className="public-section role-section"><div className="public-wrap"><div className="section-heading"><div className="eyebrow">THREE EXPERIENCES</div><h2>One arena. Different powers.</h2></div><div className="role-grid"><RoleCard role="Student" icon={<User/>} color="blue" items={["Join contests & exams","Integrated coding IDE","Instant submission results","Leaderboard & rank","Performance analytics","Achievements & profile"]}/><RoleCard role="Faculty" icon={<GraduationCap/>} color="purple" items={["Create & schedule exams","Problem & test-case builder","Student monitoring","Contest analytics","Result review","Announcements"]}/><RoleCard role="Administrator" icon={<ShieldCheck/>} color="green" items={["Institution dashboard","User & role management","System analytics","Contest governance","Security controls","Platform settings"]}/></div></div></section>
  <section id="workflow" className="public-section public-wrap"><div className="section-heading"><div className="eyebrow">HOW IT WORKS</div><h2>From problem to performance.</h2></div><div className="workflow">{["Choose a challenge","Write & test code","Submit securely","Get instant evaluation","Track your growth","Rise on the leaderboard"].map((x,i)=><div className="workflow-step" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["Join a live contest or open the practice library.","Use the IDE with language selection and custom tests.","Send your solution through the evaluation pipeline.","See passed cases, runtime, memory and status.","Turn submissions into useful analytics and insights.","Compete fairly with transparent performance metrics."][i]}</p></div>)}</div></section>
  <section className="public-wrap cta"><div><div className="eyebrow">READY TO BUILD?</div><h2>Make coding assessment feel like a product.</h2><p>Launch a modern institutional coding experience students actually want to use.</p></div><Link to="/register" className="btn light big">Enter CodeArena <ArrowRight size={17}/></Link></section>
  <footer className="public-wrap footer"><Brand/><span>© 2026 CodeArena · Built for modern coding education.</span><span>Student · Faculty · Administrator</span></footer>
 </div>
}
function RoleCard({role,icon,color,items}){return <div className={`role-card ${color}`}><div className="role-icon">{icon}</div><h3>{role}</h3><p>Purpose-built tools for the {role.toLowerCase()} experience.</p><ul>{items.map(x=><li key={x}><Check size={14}/>{x}</li>)}</ul></div>}

function Auth(){
 const [light,setLight]=useTheme(); const [mode,setMode]=useState("login"); const [role,setRole]=useState("student"); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const nav=useNavigate();
 const submit=e=>{e.preventDefault();setLoading(true);setTimeout(()=>{setLoading(false);nav(role==="student"?"/dashboard":role==="faculty"?"/faculty":"/admin")},700)};
 return <div className="auth"><div className="auth-left"><Brand/><div className="auth-hero"><div className="eyebrow">WELCOME TO CODEARENA</div><h1>One arena for<br/><span>every coder.</span></h1><p>Secure exams, competitive contests and measurable performance — all in one institutional platform.</p><div className="auth-feature"><CheckCircle2/><div><b>Smart evaluation</b><span>Consistent test-case based assessment.</span></div></div><div className="auth-feature"><BrainCircuit/><div><b>Intelligent ranking</b><span>Accuracy, efficiency and difficulty-aware scoring.</span></div></div></div></div>
 <div className="auth-right"><div className="auth-top"><Link to="/" className="back-link"><ArrowLeft size={15}/> Back home</Link><button className="theme-toggle" onClick={()=>setLight(!light)}>{light?<Moon/>:<Sun/>}</button></div><div className="auth-box"><div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Sign in</button><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Create account</button></div><h2>{mode==="login"?"Welcome back":"Create your CodeArena account"}</h2><p className="muted">Use the demo role selector to preview each experience.</p><form onSubmit={submit}>{mode==="register"&&<><label>Full name<input required placeholder="Alex Johnson"/></label><label>Institution<input placeholder="Parul University"/></label></>}<label>Email<input type="email" required placeholder="you@example.com"/></label><label>Password><div className="password"><input required type={show?"text":"password"} placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)}>{show?"Hide":"Show"}</button></div></label><div className="role-selector"><span>Continue as</span><div>{[["student","Student",User],["faculty","Faculty",GraduationCap],["admin","Administrator",ShieldCheck]].map(([v,t,I])=><button type="button" className={role===v?"selected":""} onClick={()=>setRole(v)} key={v}><I size={14}/>{t}</button>)}</div></div>{mode==="register"&&<label className="check"><input type="checkbox" required/> I agree to the platform terms.</label>}<Button primary className="submit-btn" disabled={loading}>{loading?"Opening workspace...":"Continue"} <ArrowRight size={16}/></Button></form><div className="demo-login"><KeyRound size={14}/><span>Demo frontend: choose a role above to preview its dashboard.</span></div></div></div></div>
}

const studentNav=[["/dashboard","Overview",LayoutDashboard],["/contests","Contests",Trophy],["/problems","Problems",BookOpen],["/playground","Code Playground",Terminal],["/leaderboard","Leaderboard",CrownIcon],["/submissions","Submissions",FileCode2],["/performance","Performance",BarChart3]];
const facultyNav=[["/faculty","Overview",LayoutDashboard],["/faculty/exams","Exams & Contests",CalendarDays],["/faculty/problems","Problem Bank",BookOpen],["/faculty/students","Students",Users],["/faculty/monitor","Live Monitor",Activity],["/faculty/analytics","Analytics",BarChart3]];
const adminNav=[["/admin","Overview",LayoutDashboard],["/admin/users","Users & Roles",Users],["/admin/contests","Contests",Trophy],["/admin/problems","Problem Bank",BookOpen],["/admin/audit","Audit & Security",ShieldCheck],["/admin/analytics","Platform Analytics",BarChart3],["/admin/settings","System Settings",Settings]];
function CrownIcon(){return <Trophy/>}
function AppShell({role,children}){
 const [light,setLight]=useTheme(); const [collapsed,setCollapsed]=useState(false); const [mobile,setMobile]=useState(false);
 const nav=role==="student"?studentNav:role==="faculty"?facultyNav:adminNav;
 const title=role==="student"?"Student Workspace":role==="faculty"?"Faculty Console":"Administrator Console";
 return <div className="app"><aside className={`sidebar ${collapsed?"collapsed":""} ${mobile?"open":""}`}><div className="side-brand"><Brand/><button onClick={()=>setCollapsed(!collapsed)}><PanelLeft size={16}/></button></div><div className="role-chip"><div className={`role-dot ${role}`}>{role==="student"?<User/>:role==="faculty"?<GraduationCap/>:<ShieldCheck/>}</div>{!collapsed&&<div><b>{title}</b><span>{role==="student"?"Kritarth Joshi":role==="faculty"?"Dr. Neha Sharma":"System Admin"}</span></div>}</div><nav className="side-nav">{nav.map(([to,label,I])=><NavLink end={to==="/dashboard"||to==="/faculty"||to==="/admin"} to={to} key={to} onClick={()=>setMobile(false)}><I/><span>{label}</span></NavLink>)}</nav><div className="side-bottom">{role==="student"&&<NavLink to="/profile"><User/><span>Profile</span></NavLink>}<NavLink to="/settings"><Settings/><span>Settings</span></NavLink><button onClick={()=>location.href="/"}><LogOut/><span>Sign out</span></button></div></aside><div className="app-main"><header className="app-header"><button className="mobile-only icon-btn" onClick={()=>setMobile(!mobile)}><Menu/></button><div className="global-search"><Search/><input placeholder={role==="student"?"Search problems, contests...":"Search students, exams, reports..."}/><kbd>⌘ K</kbd></div><div className="header-actions"><button className="icon-btn"><Bell/><i/></button><button className="theme-toggle" onClick={()=>setLight(!light)}>{light?<Moon/>:<Sun/>}</button><div className="header-user"><div className="avatar">{role==="student"?"KJ":role==="faculty"?"NS":"AD"}</div><div><b>{role==="student"?"Kritarth":role==="faculty"?"Dr. Neha":"Admin"}</b><span>{role}</span></div><ChevronDown size={14}/></div></div></header><main className="app-content">{children}</main></div></div>
}
function PageHead({eyebrow,title,description,children}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div><div className="page-head-actions">{children}</div></div>}
function Stat({label,value,delta,icon}){return <div className="stat"><div className="stat-label"><span>{label}</span><i>{icon}</i></div><strong>{value}</strong><small>{delta}</small></div>}
function Panel({title,sub,children,action}){return <section className="panel"><div className="panel-head"><div><h3>{title}</h3>{sub&&<p>{sub}</p>}</div>{action}</div>{children}</section>}
function Dashboard(){
 return <><PageHead eyebrow="Student dashboard" title="Good morning, Kritarth 👋" description="Your coding progress is moving in the right direction."><Link to="/contests" className="btn primary"><Trophy size={16}/> Join contest</Link></PageHead><div className="stats"><Stat label="Problems solved" value="128" delta="+12 this month" icon={<CheckCircle2/>}/><Stat label="Current rank" value="#4" delta="↑ 8 positions" icon={<Trophy/>}/><Stat label="Accuracy" value="91.4%" delta="+4.2% this month" icon={<Target/>}/><Stat label="Contest rating" value="1,987" delta="+126 this season" icon={<Zap/>}/></div><div className="grid-2"><Panel title="Performance overview" sub="Score trend over the last 7 days" action={<select><option>Last 7 days</option><option>Last 30 days</option></select>}><div className="chart"><ResponsiveContainer width="100%" height={260}><AreaChart data={activity}><defs><linearGradient id="scorefill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#6978ff" stopOpacity=".3"/><stop offset="100%" stopColor="#6978ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="day" stroke="var(--muted)" fontSize={10}/><YAxis stroke="var(--muted)" fontSize={10}/><Tooltip contentStyle={{background:"var(--tooltip)",border:"1px solid var(--line)",borderRadius:10,color:"var(--text)"}}/><Area type="monotone" dataKey="score" stroke="#6978ff" fill="url(#scorefill)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Panel><Panel title="Smart insights" sub="Personalized from your activity"><div className="insights"><Insight text="Your accuracy improved by 12% this month."/><Insight text="You solve medium problems 24% faster than average."/><Insight text="Try 2 more hard graph problems this week."/><Link to="/performance" className="text-link">View analytics <ArrowRight size={14}/></Link></div></Panel></div><div className="grid-2"><Panel title="Live & upcoming contests" sub="Your next challenges" action={<Link to="/contests" className="text-link">View all</Link>}>{contests.slice(0,3).map(c=><ContestLine c={c} key={c.id}/>)}</Panel><Panel title="Recent submissions" sub="Latest activity" action={<Link to="/submissions" className="text-link">View all</Link>}>{["Two Sum","Number of Islands","Merge Intervals","LRU Cache"].map((x,i)=><div className="simple-row" key={x}><div className="status-circle"><CheckCircle2/></div><div><b>{x}</b><span>{i%2?"C++":"Python"} · {i+1}h ago</span></div><Badge type={i===2?"wrong-answer":"accepted"}>{i===2?"Wrong Answer":"Accepted"}</Badge></div>)}</Panel></div></>
}
function Insight({text}){return <div className="insight"><Sparkles/><span>{text}</span></div>}
function ContestLine({c}){return <Link to={`/contests/${c.id}`} className="contest-line"><div className="contest-symbol"><Trophy/></div><div><b>{c.name}</b><span>{c.problems} problems · {c.participants.toLocaleString()} participants</span></div><Badge type={c.status}>{c.status}</Badge><ArrowRight size={15}/></Link>}

function Contests(){
 return <><PageHead eyebrow="Student · Competitions" title="Contests" description="Join live competitions, scheduled exams and practice events."><Button><Filter size={15}/> Filters</Button></PageHead><div className="toolbar"><div className="tabs"><button className="active">All</button><button>Live</button><button>Upcoming</button><button>Completed</button></div><div className="search-field"><Search/><input placeholder="Search contests"/></div></div><div className="contest-cards">{contests.map(c=><div className="contest-card" key={c.id}><div className="contest-top"><div className="contest-symbol big"><Trophy/></div><Badge type={c.status}>{c.status}</Badge></div><h3>{c.name}</h3><p>Curated coding challenges designed to measure real problem-solving ability.</p><div className="contest-data"><span><BookOpen/> {c.problems} problems</span><span><Users/> {c.participants.toLocaleString()}</span><span><Clock3/> {c.duration}</span></div><div className="contest-bottom"><span>{c.difficulty}</span><Link to={`/contests/${c.id}`} className="btn primary small">{c.status==="Live"?"Enter contest":"View contest"} <ArrowRight size={14}/></Link></div></div>)}</div></>
}
function Problems(){
 const [q,setQ]=useState("");const [d,setD]=useState("All");const list=problems.filter(p=>(p.title+p.topic).toLowerCase().includes(q.toLowerCase())&&(d==="All"||p.difficulty===d));
 return <><PageHead eyebrow="Student · Practice" title="Problem library" description="Practice by topic, difficulty and skill."/><div className="toolbar"><div className="search-field wide"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search problems or topics"/></div><div className="tabs">{["All","Easy","Medium","Hard"].map(x=><button key={x} className={d===x?"active":""} onClick={()=>setD(x)}>{x}</button>)}</div></div><Panel title={`${list.length} problems`} sub="Curated institutional problem bank"><div className="table-wrap"><table><thead><tr><th>Problem</th><th>Difficulty</th><th>Topic</th><th>Acceptance</th><th>Points</th><th/></tr></thead><tbody>{list.map(p=><tr key={p.id}><td><Link to={`/problems/${p.id}`} className="table-problem"><span className="number">{p.id}</span><b>{p.title}</b></Link></td><td><Badge type={p.difficulty}>{p.difficulty}</Badge></td><td>{p.topic}</td><td>{p.acceptance}%</td><td>{p.points}</td><td><Link to={`/problems/${p.id}`} className="icon-btn"><ArrowRight/></Link></td></tr>)}</tbody></table></div></Panel></>
}
function ContestDetails(){
 const {id}=useParams();const c=contests.find(x=>x.id==id)||contests[0];
 return <><PageHead eyebrow="Contest" title={c.name} description={`${c.difficulty} · ${c.problems} problems · ${c.duration}`}><div className="countdown"><Clock3/> {c.status==="Live"?"00:24:17":"Starts "+c.time}</div></PageHead><div className="grid-2 contest-detail"><Panel title="Problems" sub="Choose a challenge to begin"><div>{problems.slice(0,c.problems).map((p,i)=><Link className="problem-line" to={`/problems/${p.id}`} key={p.id}><span className="letter">{String.fromCharCode(65+i)}</span><div><b>{p.title}</b><span>{p.topic} · {p.points} points</span></div><Badge type={p.difficulty}>{p.difficulty}</Badge>{i<2?<CheckCircle2 className="success"/>:<ChevronRight/>}</Link>)}</div></Panel><Panel title="Contest snapshot" sub="Your live standing"><div className="score-big">420 <small>/ 1000</small></div><div className="progress"><span style={{width:"42%"}}/></div>{[["Your rank","#47 / 1,248"],["Solved","2 / 5"],["Time remaining","24m 17s"],["Smart score","86.2"]].map(([a,b])=><div className="info-line" key={a}><span>{a}</span><b>{b}</b></div>)}<Link to="/leaderboard" className="btn full">View leaderboard <ArrowRight size={15}/></Link></Panel></div></>
}
function Problem(){
 const {id}=useParams();const p=problems.find(x=>x.id==id)||problems[0];const [code,setCode]=useState(initialCode);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 const run=()=>{setBusy(true);setStatus("Running test cases...");setTimeout(()=>{setBusy(false);setStatus("Accepted · 12/12 tests passed · 42 ms · 14.2 MB")},1000)};
 return <div className="ide"><div className="ide-bar"><Link to="/problems"><ArrowLeft size={15}/> Problems</Link><div><b>{p.title}</b><Badge type={p.difficulty}>{p.difficulty}</Badge></div><div className="ide-actions"><select><option>Python</option><option>C++</option><option>Java</option><option>JavaScript</option></select><Button small onClick={run}><Play size={14}/> Run</Button><Button primary small onClick={run}>{busy?"Submitting...":"Submit"} <Send size={14}/></Button></div></div><div className="ide-main"><article className="problem-statement"><div className="tabs"><button className="active">Description</button><button>Editorial</button></div><h1>{p.title}</h1><div className="problem-tags"><Badge type={p.difficulty}>{p.difficulty}</Badge><span>{p.topic}</span><span>{p.points} points</span></div><h3>Problem statement</h3><p>Given an array of integers <code>nums</code> and an integer <code>target</code>, return indices of the two numbers such that they add up to target. You may assume each input has exactly one solution.</p><h3>Constraints</h3><ul><li>2 ≤ nums.length ≤ 10,000</li><li>-10⁹ ≤ nums[i] ≤ 10⁹</li><li>Each input has exactly one valid answer.</li></ul><h3>Example</h3><pre className="example">Input: nums = [2,7,11,15], target = 9{"\n"}Output: [0,1]</pre></article><div className="code-side"><div className="editor-label"><span><FileCode2/> solution.py</span><span>Python 3.12</span></div><Editor height="100%" language="python" theme={document.documentElement.dataset.theme==="light"?"light":"vs-dark"} value={code} onChange={v=>setCode(v||"")} options={{minimap:{enabled:false},fontSize:14,automaticLayout:true,padding:{top:14},roundedSelection:false}}/><div className="console"><div className="console-tabs"><button className="active">Test cases</button><button>Custom input</button><button>Output</button></div><div className="console-result">{status?<><CheckCircle2 className="success"/><div><b>{status.split(" · ")[0]}</b><span>{status.includes(" · ")?status.split(" · ").slice(1).join(" · "):"Please wait..."}</span></div></>:<div className="test-cases"><span>✓ Case 1</span><span>✓ Case 2</span><span>✓ Case 3</span><span>✓ Case 4</span></div>}</div></div></div></div></div>
}
function Playground(){return <div className="ide"><div className="ide-bar"><div><Terminal size={16}/> <b>Code Playground</b></div><div className="ide-actions"><select><option>Python</option><option>C++</option><option>Java</option></select><Button small><Upload size={14}/> Save</Button><Button primary small><Play size={14}/> Run</Button></div></div><div className="playground"><aside><b>EXPLORER</b><span>▾ workspace</span><span className="file active">▣ main.py</span><span className="file">▣ utils.py</span><span className="file">▣ README.md</span></aside><div><Editor height="100%" language="python" theme={document.documentElement.dataset.theme==="light"?"light":"vs-dark"} defaultValue={initialCode} options={{minimap:{enabled:false},fontSize:14,automaticLayout:true}}/></div><section className="play-console"><b><Terminal size={14}/> Console</b><pre>CodeArena Python 3.12{"\n"}Ready to execute your code.{"\n"}<span>$</span> _</pre></section></div></div>
}
function Leaderboard(){
 return <><PageHead eyebrow="Competition" title="Leaderboard" description="Transparent performance rankings across the institution."><Button><Filter size={15}/> Filters</Button></PageHead><div className="podium">{leaderboard.slice(0,3).map((x,i)=><div className={`podium-card ${i===0?"second":i===1?"first":"third"}`} key={x.rank}><span>{i===0?"🥈":i===1?"🥇":"🥉"}</span><div className="avatar large">{x.name.split(" ").map(a=>a[0]).join("")}</div><b>#{x.rank} {x.name}</b><strong>{x.score}</strong><small>Smart score {x.smart}</small></div>)}</div><Panel title="Institution leaderboard" sub="Smart ranking enabled"><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Coder</th><th>Score</th><th>Solved</th><th>Accuracy</th><th>Time</th><th>Smart score</th></tr></thead><tbody>{leaderboard.map(x=><tr className={x.name.includes("Kritarth")?"highlight":""} key={x.rank}><td>#{x.rank}</td><td><div className="person"><div className="avatar">{x.name.split(" ").map(a=>a[0]).join("")}</div><b>{x.name}</b>{x.name.includes("Kritarth")&&<Badge>YOU</Badge>}</div></td><td>{x.score}</td><td>{x.solved}</td><td>{x.accuracy}%</td><td>{x.time}</td><td><b className="accent">{x.smart}</b></td></tr>)}</tbody></table></div></Panel><div className="smart-callout"><BrainCircuit/><div><b>Smart ranking</b><p>Rankings combine accuracy, time efficiency, problem difficulty and submission patterns to produce a more balanced performance score.</p></div></div></>
}
function Submissions(){return <><PageHead eyebrow="Student · History" title="Submission history" description="Every attempt, status and execution metric."/><div className="stats"><Stat label="Total submissions" value="342" delta="+18 this week" icon={<FileCode2/>}/><Stat label="Accepted" value="289" delta="84.5% success" icon={<CheckCircle2/>}/><Stat label="Average runtime" value="76ms" delta="-12ms this month" icon={<Zap/>}/><Stat label="Current streak" value="7 days" delta="Personal best" icon={<Flame/>}/></div><Panel title="All submissions" sub="Latest attempts"><div className="table-wrap"><table><thead><tr><th>ID</th><th>Problem</th><th>Language</th><th>Status</th><th>Runtime</th><th>Memory</th><th>Time</th></tr></thead><tbody>{Array.from({length:8},(_,i)=><tr key={i}><td><code>SUB-{90421-i*31}</code></td><td><b>{problems[i%problems.length].title}</b></td><td>{i%3===0?"Python":i%3===1?"C++":"Java"}</td><td><Badge type={i===2?"wrong-answer":"accepted"}>{i===2?"Wrong Answer":"Accepted"}</Badge></td><td>{42+i*7} ms</td><td>{14+i}.2 MB</td><td>{i+1}h ago</td></tr>)}</tbody></table></div></Panel></>}
function Performance(){return <><PageHead eyebrow="Student · Intelligence" title="Performance analytics" description="Understand your strengths, weaknesses and progress."/><div className="stats"><Stat label="Problems solved" value="128" delta="+12 this month" icon={<CheckCircle2/>}/><Stat label="Accuracy" value="91.4%" delta="+4.2%" icon={<Target/>}/><Stat label="Avg solve time" value="18m" delta="-18%" icon={<Clock3/>}/><Stat label="Best rank" value="#2" delta="Weekly contest" icon={<Trophy/>}/></div><div className="grid-2"><Panel title="Score trend" sub="Last 7 days"><div className="chart"><ResponsiveContainer width="100%" height={280}><LineChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="day" stroke="var(--muted)"/><YAxis stroke="var(--muted)"/><Tooltip contentStyle={{background:"var(--tooltip)",border:"1px solid var(--line)"}}/><Line type="monotone" dataKey="score" stroke="#6978ff" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Panel><Panel title="Submission volume" sub="Daily attempts"><div className="chart"><ResponsiveContainer width="100%" height={280}><BarChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="day" stroke="var(--muted)"/><YAxis stroke="var(--muted)"/><Tooltip contentStyle={{background:"var(--tooltip)",border:"1px solid var(--line)"}}/><Bar dataKey="sub" fill="#63c9e8" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel></div><div className="grid-3"><Panel title="Strengths"><TagBar label="Arrays" value={92}/><TagBar label="Strings" value={89}/><TagBar label="Stack" value={86}/></Panel><Panel title="Needs practice"><TagBar label="Graphs" value={64}/><TagBar label="DP" value={69}/><TagBar label="Trees" value={71}/></Panel><Panel title="Smart recommendation"><div className="recommend"><BrainCircuit/><b>Next focus: Graphs</b><p>Complete 3 medium graph problems this week to close your largest skill gap.</p><Link to="/problems" className="text-link">Practice now <ArrowRight size={14}/></Link></div></Panel></div></>}
function TagBar({label,value}){return <div className="tagbar"><div><span>{label}</span><b>{value}%</b></div><div><i style={{width:value+"%"}}/></div></div>}
function Profile(){return <><PageHead eyebrow="Student · Profile" title="Kritarth Joshi" description="Your coding identity, achievements and activity."><Button><Edit3 size={15}/> Edit profile</Button></PageHead><div className="grid-profile"><Panel title="Profile"><div className="profile-main"><div className="profile-avatar">KJ</div><h2>Kritarth Joshi</h2><p>Student · Parul University</p><span><Globe2/> India</span></div><div className="profile-stats"><div><b>128</b><span>Solved</span></div><div><b>1,987</b><span>Rating</span></div><div><b>#4</b><span>Rank</span></div></div></Panel><Panel title="Achievements" sub="Milestones unlocked"><div className="achievement-grid">{["⚡ First Submit","🔥 7 Day Streak","🏆 Contest Winner","💯 100 Problems","🚀 Top 10%","🧠 Smart Solver"].map(x=><div className="achievement" key={x}><strong>{x}</strong><small>Unlocked</small></div>)}</div></Panel></div><Panel title="Coding activity" sub="Last 90 days"><div className="heatmap">{Array.from({length:126},(_,i)=><i className={`heat h${i%5}`} key={i}/>)}</div></Panel></>}
function SettingsPage(){const [light,setLight]=useTheme();return <><PageHead eyebrow="Preferences" title="Settings" description="Manage account, notifications and appearance."/><div className="settings-layout"><nav><button className="active">Account</button><button>Security</button><button>Notifications</button><button>Appearance</button></nav><Panel title="Account settings" sub="Profile information"><label>Full name<input value="Kritarth Joshi" readOnly/></label><label>Email<input value="kritarth@example.com" readOnly/></label><label>Institution<input value="Parul University" readOnly/></label><div className="setting-row"><div><b>Theme</b><span>Switch between light and dark interfaces.</span></div><Button onClick={()=>setLight(!light)}>{light?<Moon/>:<Sun/>}{light?"Dark mode":"Light mode"}</Button></div></Panel></div></>}

function FacultyHome(){return <><PageHead eyebrow="Faculty console" title="Good morning, Dr. Neha 👋" description="Monitor assessments, student progress and today's schedule."><Button primary><Plus size={16}/> Create exam</Button></PageHead><div className="stats"><Stat label="Active exams" value="6" delta="2 live now" icon={<CalendarDays/>}/><Stat label="Students" value="1,842" delta="+96 this term" icon={<Users/>}/><Stat label="Submissions today" value="2,481" delta="+14.8%" icon={<FileCode2/>}/><Stat label="Avg class score" value="78.6%" delta="+3.8%" icon={<Target/>}/></div><div className="grid-2"><Panel title="Today's schedule" sub="Upcoming faculty events"><Schedule title="DSA Mid-Sem Assessment" time="10:00 AM – 12:00 PM" status="Live" count="142 students"/><Schedule title="Python Lab Evaluation" time="2:30 PM – 4:00 PM" status="Upcoming" count="86 students"/><Schedule title="Weekly Practice Contest" time="5:30 PM – 7:00 PM" status="Upcoming" count="210 students"/></Panel><Panel title="Class performance" sub="Average score by batch"><div className="chart"><ResponsiveContainer width="100%" height={240}><BarChart data={[{x:"CSE-A",v:84},{x:"CSE-B",v:79},{x:"AI-1",v:88},{x:"AI-2",v:76},{x:"IT-A",v:81}]}><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="x" stroke="var(--muted)"/><YAxis stroke="var(--muted)"/><Tooltip/><Bar dataKey="v" fill="#8b72ff" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel></div><div className="grid-3"><Panel title="Pending review"><Queue icon={<FileCode2/>} title="27 manual reviews" text="Submissions flagged for faculty review."/></Panel><Panel title="At-risk students"><Queue icon={<AlertCircle/>} title="18 students" text="Below 60% in the current assessment."/></Panel><Panel title="Announcements"><Queue icon={<MessageSquare/>} title="3 scheduled" text="Next announcement goes out at 4:00 PM."/></Panel></div></>}
function Schedule({title,time,status,count}){return <div className="schedule"><div className="calendar-icon"><CalendarDays/></div><div><b>{title}</b><span>{time} · {count}</span></div><Badge type={status}>{status}</Badge></div>}
function Queue({icon,title,text}){return <div className="queue"><div>{icon}</div><b>{title}</b><p>{text}</p><ArrowRight/></div>}
function FacultyExams(){return <><PageHead eyebrow="Faculty · Management" title="Exams & contests" description="Create, schedule, publish and review coding assessments."><Button primary><Plus size={16}/> New assessment</Button></PageHead><div className="toolbar"><div className="tabs"><button className="active">All</button><button>Drafts</button><button>Scheduled</button><button>Live</button><button>Completed</button></div><div className="search-field"><Search/><input placeholder="Search assessments"/></div></div><Panel title="Assessments" sub="Institutional coding evaluations"><div className="table-wrap"><table><thead><tr><th>Assessment</th><th>Status</th><th>Class</th><th>Problems</th><th>Participants</th><th>Schedule</th><th/></tr></thead><tbody>{["DSA Mid-Sem Assessment","Python Lab Evaluation","Weekly Practice Contest","Algorithms Final","SQL Challenge"].map((x,i)=><tr key={x}><td><b>{x}</b></td><td><Badge type={i===0?"live":i<3?"upcoming":"completed"}>{i===0?"Live":i<3?"Upcoming":"Completed"}</Badge></td><td>{i%2?"AI-2":"CSE-A"}</td><td>{5+i}</td><td>{142+i*24}</td><td>{i===0?"Today, 10:00 AM":`Aug ${22+i}, 2026`}</td><td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></Panel></>}
function FacultyProblems(){return <><PageHead eyebrow="Faculty · Content" title="Problem bank" description="Curate reusable problems and test cases."><Button primary><Plus/> Add problem</Button></PageHead><Panel title="Institution problem bank" sub="584 problems"><div className="table-wrap"><table><thead><tr><th>Problem</th><th>Difficulty</th><th>Topic</th><th>Points</th><th>Test cases</th><th>Usage</th><th/></tr></thead><tbody>{problems.map(p=><tr key={p.id}><td><b>{p.title}</b></td><td><Badge type={p.difficulty}>{p.difficulty}</Badge></td><td>{p.topic}</td><td>{p.points}</td><td>{12+p.id}</td><td>{14+p.id*3} contests</td><td><button className="icon-btn"><Edit3/></button></td></tr>)}</tbody></table></div></Panel></>}
function FacultyStudents(){return <><PageHead eyebrow="Faculty · Students" title="Student performance" description="Monitor your classes and identify where support is needed."/><div className="stats"><Stat label="Students monitored" value="1,842" delta="Across 8 classes" icon={<Users/>}/><Stat label="Avg accuracy" value="78.6%" delta="+3.8%" icon={<Target/>}/><Stat label="At risk" value="18" delta="-7 this week" icon={<AlertCircle/>}/><Stat label="Top performers" value="124" delta="Above 90%" icon={<Trophy/>}/></div><Panel title="Student directory"><div className="table-wrap"><table><thead><tr><th>Student</th><th>Class</th><th>Problems</th><th>Accuracy</th><th>Last active</th><th>Risk</th></tr></thead><tbody>{leaderboard.concat(leaderboard).map((x,i)=><tr key={i}><td><div className="person"><div className="avatar">{x.name.split(" ").map(a=>a[0]).join("")}</div><b>{x.name}</b></div></td><td>{i%2?"AI-2":"CSE-A"}</td><td>{x.solved*12}</td><td>{x.accuracy}%</td><td>{i+1}h ago</td><td><Badge type={x.accuracy<90?"medium":"accepted"}>{x.accuracy<90?"Watch":"Healthy"}</Badge></td></tr>)}</tbody></table></div></Panel></>}
function FacultyMonitor(){return <><PageHead eyebrow="Faculty · Live monitor" title="DSA Mid-Sem Assessment" description="Live classroom monitoring and evaluation status."><div className="countdown"><Activity/> LIVE · 01:18:42 remaining</div></PageHead><div className="stats"><Stat label="Participants" value="142/150" delta="94.7% joined" icon={<Users/>}/><Stat label="Submissions" value="1,284" delta="+42 in last 5 min" icon={<Send/>}/><Stat label="Accepted" value="72.8%" delta="Stable" icon={<CheckCircle2/>}/><Stat label="Flagged" value="7" delta="Needs review" icon={<AlertCircle/>}/></div><div className="grid-2"><Panel title="Live submission stream" sub="Newest submissions first">{["Aarav Mehta","Diya Shah","Rohan Patel","Ananya Rao","Dev Malhotra","Kritarth Joshi"].map((n,i)=><div className="simple-row" key={n}><div className="avatar">{n.split(" ").map(a=>a[0]).join("")}</div><div><b>{n}</b><span>{problems[i].title} · Python · {i+1}s ago</span></div><Badge type={i===2?"wrong-answer":"accepted"}>{i===2?"Wrong Answer":"Accepted"}</Badge></div>)}</Panel><Panel title="Problem distribution" sub="Solved by participants"><div className="chart"><ResponsiveContainer width="100%" height={280}><BarChart data={problems.slice(0,6).map((p,i)=>({x:String.fromCharCode(65+i),v:70-i*7}))}><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="x" stroke="var(--muted)"/><YAxis stroke="var(--muted)"/><Tooltip/><Bar dataKey="v" fill="#62cfe7" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Panel></div></>}
function FacultyAnalytics(){return <><PageHead eyebrow="Faculty · Analytics" title="Assessment analytics" description="Understand class outcomes and problem quality."><Button><Download size={15}/> Export report</Button></PageHead><div className="stats"><Stat label="Average score" value="78.6%" delta="+3.8% vs last exam" icon={<Target/>}/><Stat label="Completion rate" value="91.2%" delta="+4.1%" icon={<CheckCircle2/>}/><Stat label="Avg solve time" value="24m" delta="-11%" icon={<Clock3/>}/><Stat label="Problem quality" value="87%" delta="Based on outcomes" icon={<BrainCircuit/>}/></div><div className="grid-2"><Panel title="Class score trend"><div className="chart"><ResponsiveContainer width="100%" height={300}><LineChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="day" stroke="var(--muted)"/><YAxis stroke="var(--muted)"/><Tooltip/><Line dataKey="score" stroke="#8b72ff" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Panel><Panel title="Difficulty performance"><div className="chart"><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={[{name:"Easy",value:92},{name:"Medium",value:76},{name:"Hard",value:58}]} dataKey="value" nameKey="name" outerRadius={100} label><Cell fill="#56d59c"/><Cell fill="#f0bd54"/><Cell fill="#ff7186"/></Pie><Tooltip/></PieChart></ResponsiveContainer></div></Panel></div></>}
function AdminHome(){return <><PageHead eyebrow="Administrator · Platform" title="Institution overview" description="Govern the complete CodeArena environment."><Button primary><Plus/> Create institution event</Button></PageHead><div className="stats"><Stat label="Total users" value="8,426" delta="+284 this month" icon={<Users/>}/><Stat label="Active contests" value="12" delta="4 live now" icon={<Trophy/>}/><Stat label="Problems" value="584" delta="+36 this month" icon={<BookOpen/>}/><Stat label="Submissions today" value="4,821" delta="+18.4%" icon={<Activity/>}/></div><div className="grid-2"><Panel title="Platform activity" sub="Submissions across all departments"><div className="chart"><ResponsiveContainer width="100%" height={270}><AreaChart data={activity}><defs><linearGradient id="adminfill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#62cfe7" stopOpacity=".3"/><stop offset="100%" stopColor="#62cfe7" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="day" stroke="var(--muted)"/><YAxis stroke="var(--muted)"/><Tooltip/><Area dataKey="sub" stroke="#62cfe7" fill="url(#adminfill)"/></AreaChart></ResponsiveContainer></div></Panel><Panel title="System health" sub="All services operational"><Health name="Authentication" value="99.99%"/><Health name="Evaluation engine" value="99.96%"/><Health name="Database" value="99.99%"/><Health name="Realtime leaderboard" value="99.94%"/></Panel></div><div className="grid-3"><Panel title="Role distribution"><div className="role-count"><b>6,842</b><span>Students</span></div><div className="role-count"><b>214</b><span>Faculty</span></div><div className="role-count"><b>18</b><span>Administrators</span></div></Panel><Panel title="Security"><Queue icon={<ShieldCheck/>} title="No critical events" text="Last audit completed successfully."/></Panel><Panel title="System announcements"><Queue icon={<Bell/>} title="2 scheduled" text="Next maintenance window: Sunday 02:00."/></Panel></div></>}
function Health({name,value}){return <div className="health"><span className="health-dot"/><div><b>{name}</b><small>Operational</small></div><strong>{value}</strong></div>}
function AdminUsers(){return <><PageHead eyebrow="Administrator · Governance" title="Users & roles" description="Manage students, faculty and administrators."><Button primary><Plus/> Invite user</Button></PageHead><div className="toolbar"><div className="tabs"><button className="active">All users</button><button>Students</button><button>Faculty</button><button>Admins</button></div><div className="search-field"><Search/><input placeholder="Search by name, email or ID"/></div></div><Panel title="User directory" sub="8,426 accounts"><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Department</th><th>Last active</th><th>Status</th><th/></tr></thead><tbody>{leaderboard.concat(leaderboard).map((x,i)=><tr key={i}><td><div className="person"><div className="avatar">{x.name.split(" ").map(a=>a[0]).join("")}</div><div><b>{x.name}</b><span>{x.name.toLowerCase().replaceAll(" ",".")+"@university.edu"}</span></div></div></td><td><Badge>{i%7===0?"Administrator":i%3===0?"Faculty":"Student"}</Badge></td><td>{i%2?"Computer Science":"AI & Data Science"}</td><td>{i+1}h ago</td><td><Badge type="accepted">Active</Badge></td><td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></Panel></>}
function AdminContests(){return <><PageHead eyebrow="Administrator · Governance" title="Contests & exams" description="Control the institutional assessment calendar."><Button primary><Plus/> Create contest</Button></PageHead><Panel title="All assessments" sub="12 active · 48 completed"><div className="table-wrap"><table><thead><tr><th>Assessment</th><th>Status</th><th>Owner</th><th>Problems</th><th>Participants</th><th>Schedule</th><th/></tr></thead><tbody>{contests.concat(contests).map((c,i)=><tr key={i}><td><b>{c.name}</b></td><td><Badge type={c.status}>{c.status}</Badge></td><td>Dr. Neha Sharma</td><td>{c.problems}</td><td>{c.participants}</td><td>Aug {21+i}, 2026</td><td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></Panel></>}
function AdminProblems(){return <><PageHead eyebrow="Administrator · Content" title="Problem bank" description="Institution-wide coding content and test-case governance."><Button primary><Plus/> Add problem</Button></PageHead><Panel title="Master problem bank" sub="584 problems"><div className="table-wrap"><table><thead><tr><th>Problem</th><th>Difficulty</th><th>Topic</th><th>Points</th><th>Usage</th><th>Quality</th><th/></tr></thead><tbody>{problems.map(p=><tr key={p.id}><td><b>{p.title}</b></td><td><Badge type={p.difficulty}>{p.difficulty}</Badge></td><td>{p.topic}</td><td>{p.points}</td><td>{14+p.id*4}</td><td>{p.acceptance>70?"Excellent":"Review"}</td><td><button className="icon-btn"><Edit3/></button></td></tr>)}</tbody></table></div></Panel></>}
function AdminAudit(){return <><PageHead eyebrow="Administrator · Security" title="Audit & security" description="Monitor access, role changes and sensitive platform actions."><Badge type="accepted">All systems operational</Badge></PageHead><div className="stats"><Stat label="Security events" value="12" delta="-31% this month" icon={<ShieldCheck/>}/><Stat label="Failed logins" value="47" delta="-18% this week" icon={<KeyRound/>}/><Stat label="Admin sessions" value="18" delta="4 active now" icon={<Users/>}/><Stat label="Audit coverage" value="100%" delta="All critical actions" icon={<CheckCircle2/>}/></div><Panel title="Recent audit events" sub="Latest platform security activity"><div className="audit-list">{["Admin role granted to faculty@university.edu","Contest published: Campus Championship","Password reset requested by STU-2026124","Faculty permissions updated","New administrator session started"].map((x,i)=><div className="audit" key={x}><div><ShieldCheck/></div><span><b>{x}</b><small>{i+2} hours ago · IP 10.24.18.{20+i}</small></span><Badge>{i===0?"Role change":"System"}</Badge></div>)}</div></Panel></>}
function AdminAnalytics(){return <><PageHead eyebrow="Administrator · Intelligence" title="Platform analytics" description="Institution-wide performance, participation and evaluation quality."><Button><Download/> Export report</Button></PageHead><div className="stats"><Stat label="Average score" value="78.6%" delta="+3.8% this term" icon={<Target/>}/><Stat label="Completion rate" value="84.2%" delta="+6.1%" icon={<CheckCircle2/>}/><Stat label="Peak concurrent" value="1,842" delta="Weekly #42" icon={<Users/>}/><Stat label="Evaluation uptime" value="99.96%" delta="Excellent" icon={<Zap/>}/></div><div className="grid-2"><Panel title="Institution activity"><div className="chart"><ResponsiveContainer width="100%" height={300}><LineChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="day" stroke="var(--muted)"/><YAxis stroke="var(--muted)"/><Tooltip/><Line dataKey="sub" stroke="#6978ff" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Panel><Panel title="Problem difficulty mix"><div className="chart"><ResponsiveContainer width="100%" height={300}><PieChart><Pie data={[{name:"Easy",value:42},{name:"Medium",value:39},{name:"Hard",value:19}]} dataKey="value" nameKey="name" outerRadius={100} label><Cell fill="#56d59c"/><Cell fill="#f0bd54"/><Cell fill="#ff7186"/></Pie><Tooltip/></PieChart></ResponsiveContainer></div></Panel></div></>}
function AdminSettings(){const [light,setLight]=useTheme();return <><PageHead eyebrow="Administrator · System" title="System settings" description="Configure the institution-wide CodeArena environment."/><div className="settings-layout"><nav><button className="active">General</button><button>Authentication</button><button>Evaluation</button><button>Notifications</button><button>Branding</button></nav><Panel title="General settings" sub="Core platform preferences"><label>Institution name<input value="Parul University" readOnly/></label><label>Default contest duration<input value="90 minutes" readOnly/></label><div className="setting-row"><div><b>Theme default</b><span>Choose the default appearance for new users.</span></div><Button onClick={()=>setLight(!light)}>{light?<Moon/>:<Sun/>}{light?"Dark":"Light"} mode</Button></div><div className="setting-row"><div><b>Secure execution</b><span>Sandbox user-submitted code before evaluation.</span></div><span className="switch on"><i/></span></div></Panel></div></>}

function FacultyLayout({children}){return <AppShell role="faculty">{children}</AppShell>}
function AdminLayout({children}){return <AppShell role="admin">{children}</AppShell>}
function StudentLayout({children}){return <AppShell role="student">{children}</AppShell>}

function App(){
 const [light]=useTheme();
 return <Routes>
  <Route path="/" element={<Landing/>}/><Route path="/login" element={<Auth/>}/><Route path="/register" element={<Auth/>}/>
  <Route path="/dashboard" element={<StudentLayout><Dashboard/></StudentLayout>}/><Route path="/contests" element={<StudentLayout><Contests/></StudentLayout>}/><Route path="/contests/:id" element={<StudentLayout><ContestDetails/></StudentLayout>}/><Route path="/problems" element={<StudentLayout><Problems/></StudentLayout>}/><Route path="/problems/:id" element={<Problem/>}/><Route path="/playground" element={<StudentLayout><Playground/></StudentLayout>}/><Route path="/leaderboard" element={<StudentLayout><Leaderboard/></StudentLayout>}/><Route path="/submissions" element={<StudentLayout><Submissions/></StudentLayout>}/><Route path="/performance" element={<StudentLayout><Performance/></StudentLayout>}/><Route path="/profile" element={<StudentLayout><Profile/></StudentLayout>}/><Route path="/settings" element={<StudentLayout><SettingsPage/></StudentLayout>}/>
  <Route path="/faculty" element={<FacultyLayout><FacultyHome/></FacultyLayout>}/><Route path="/faculty/exams" element={<FacultyLayout><FacultyExams/></FacultyLayout>}/><Route path="/faculty/problems" element={<FacultyLayout><FacultyProblems/></FacultyLayout>}/><Route path="/faculty/students" element={<FacultyLayout><FacultyStudents/></FacultyLayout>}/><Route path="/faculty/monitor" element={<FacultyLayout><FacultyMonitor/></FacultyLayout>}/><Route path="/faculty/analytics" element={<FacultyLayout><FacultyAnalytics/></FacultyLayout>}/>
  <Route path="/admin" element={<AdminLayout><AdminHome/></AdminLayout>}/><Route path="/admin/users" element={<AdminLayout><AdminUsers/></AdminLayout>}/><Route path="/admin/contests" element={<AdminLayout><AdminContests/></AdminLayout>}/><Route path="/admin/problems" element={<AdminLayout><AdminProblems/></AdminLayout>}/><Route path="/admin/audit" element={<AdminLayout><AdminAudit/></AdminLayout>}/><Route path="/admin/analytics" element={<AdminLayout><AdminAnalytics/></AdminLayout>}/><Route path="/admin/settings" element={<AdminLayout><AdminSettings/></AdminLayout>}/>
  <Route path="*" element={<NotFound/>}/>
 </Routes>
}
function NotFound(){return <div className="notfound"><Brand/><h1>404</h1><p>That page doesn't exist.</p><Link to="/" className="btn primary">Back home</Link></div>}
createRoot(document.getElementById("root")).render(<BrowserRouter><App/></BrowserRouter>);
